
csrf_secret = "REPLACE-ME"

[pg]
user = "appuser"
password = "changeme"
database_name = "appdb"
hostname = "postgres"
port = 5432

[jwt]
private_key = """-----BEGIN PRIVATE KEY-----
REPLACE-ME
-----END PRIVATE KEY-----"""
public_key = """-----BEGIN PUBLIC KEY-----
REPLACE-ME
-----END PUBLIC KEY-----"""


[redis]
url = "redis://redis:6379/0"
