version = "0.1.0"

[app]
name = "FastAPI Backend Template"
description = "A template for building FastAPI applications."
debug = true
openapi_url = "/openapi.json"
docs_url = "/docs"
redoc_url = "/redoc"
allow_doc_routes = true

[cors]
allow_origins = ["*"]
allow_credentials = true
allow_methods = ["*"]
allow_headers = ["*"]

[sql_alchemy]
pool_size = 10
max_overflow = 20
pool_timeout = 30
pool_recycle = 1800
echo = true
future = true

[logger]
# format = "good default"
level = 'DEBUG'
retention_days = 7
rotation_mb = 5
compression = 'zip'
security_level_no = 25
structured_logs = true

[redis]
socket_connect_timeout = 5
retry_on_timeout = true
max_connections = 10
socket_keepalive = true
decode_responses = true
health_check_interval = 30
socket_timeout = 5